#ifndef RTC_H
#define RTC_H

#include "rush.h"

#define RTC_ADDRESS 0b1010000

#define SELECT_CONTROL_REGISTER1	0x00
#define SELECT_CONTROL_REGISTER2	0x01
#define SELECT_CLKOUT_REGISTER		0x0D
#define SELECT_TIMER_REGISTER		0x0E
#define SELECT_SECONDS_REGISTER		0x02

#define SELECT_

#endif
